# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: lender_app_db
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db